In [1]:
import numpy as np

In [4]:
## one dimensional array
arr_1 = np.array([2,19,2,15,100,50,6,79,88])
arr_1

array([  2,  19,   2,  15, 100,  50,   6,  79,  88])

In [5]:
type(arr_1)

numpy.ndarray

In [7]:
arr_1.ndim

1

In [8]:
arr_1.size

9

In [9]:
arr_1[4]

np.int64(100)

In [10]:
arr_1[:4]

array([ 2, 19,  2, 15])

In [11]:
## mutabile
arr_1[4] = 200

In [12]:
## insert cannot change the data permenantly 
np.insert(arr_1,4,100)

array([  2,  19,   2,  15, 100, 200,  50,   6,  79,  88])

In [13]:
arr_1

array([  2,  19,   2,  15, 200,  50,   6,  79,  88])

In [14]:
## but by putting that into a new variable we can create a new array using that
arr_1_dummy = np.insert(arr_1,4,100)

In [15]:
arr_1_dummy

array([  2,  19,   2,  15, 100, 200,  50,   6,  79,  88])

In [16]:
##same for delete also
np.delete(arr_1,4)

array([ 2, 19,  2, 15, 50,  6, 79, 88])

In [17]:
arr_1

array([  2,  19,   2,  15, 200,  50,   6,  79,  88])

In [18]:
arr_1_delete_dummy = np.delete(arr_1,4)

In [19]:
arr_1_delete_dummy

array([ 2, 19,  2, 15, 50,  6, 79, 88])